project:
  subject: "WINS Project Config"

---
spring:
  profiles: stage

project:
  subject: "WINS Project Config for Stage"

---
spring:
  profiles: dev

project:
  subject: "WINS Project Config for Dev"

---
spring:
  profiles: local

project:
  subject: "WINS Project Config for local "