---
spring:
  profiles: default

project:
  subject: "WINS Project Config for local "


---
spring:
  profiles: local

project:
  subject: "WINS Project Config for local "

---
spring:
  profiles: production

project:
  subject: "WINS Project Config"

---
spring:
  profiles: stage

project:
  subject: "WINS Project Config for Stage"

---
spring:
  profiles: dev

project:
  subject: "WINS Project Config for Dev"

